# .streamlit/secrets.toml

# Clave de API de Google
google_api_key = "AIzaSyAGceBNFOdOke-sH1VbbNUpPGahOVhwMA8"

# Credenciales de la Base de Datos
[db_credentials]
user = "u241824557_than"
password = "1541100Luis"
host = "82.197.82.125"

database = "u241824557_lbusiness"

